name:                 avl-tree
version:              0.1.0.0
visibility:           public
id:                   avl-tree-0.1.0.0-inplace
key:                  avl-tree-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           ordonezmarcos935@gmail.com
author:               marcos-ordo
category:             Data
abi:                  inplace
exposed:              True
exposed-modules:      AVL
import-dirs:
    /home/marcoso/code/haskell/avl_tree/dist-newstyle/build/x86_64-linux/ghc-9.6.7/avl-tree-0.1.0.0/build

library-dirs:
    /home/marcoso/code/haskell/avl_tree/dist-newstyle/build/x86_64-linux/ghc-9.6.7/avl-tree-0.1.0.0/build

library-dirs-static:
    /home/marcoso/code/haskell/avl_tree/dist-newstyle/build/x86_64-linux/ghc-9.6.7/avl-tree-0.1.0.0/build

dynamic-library-dirs:
    /home/marcoso/code/haskell/avl_tree/dist-newstyle/build/x86_64-linux/ghc-9.6.7/avl-tree-0.1.0.0/build

data-dir:             /home/marcoso/code/haskell/avl_tree/.
hs-libraries:         HSavl-tree-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /home/marcoso/code/haskell/avl_tree/dist-newstyle/build/x86_64-linux/ghc-9.6.7/avl-tree-0.1.0.0/doc/html/avl-tree/avl-tree.haddock

haddock-html:
    /home/marcoso/code/haskell/avl_tree/dist-newstyle/build/x86_64-linux/ghc-9.6.7/avl-tree-0.1.0.0/doc/html/avl-tree
